# CMake generated Testfile for 
# Source directory: /Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent
# Build directory: /Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_corpus
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(edr_agent_help "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_corpus/edr_agent" "--help")
set_tests_properties(edr_agent_help PROPERTIES  _BACKTRACE_TRIPLES "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;470;add_test;/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;0;")
add_test(ave_behavior_features_m3a "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_corpus/test_ave_behavior_features_m3a")
set_tests_properties(ave_behavior_features_m3a PROPERTIES  WORKING_DIRECTORY "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_corpus" _BACKTRACE_TRIPLES "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;723;add_test;/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;0;")
add_test(ave_cross_engine_parse "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_corpus/test_ave_cross_engine_parse")
set_tests_properties(ave_cross_engine_parse PROPERTIES  WORKING_DIRECTORY "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_corpus" _BACKTRACE_TRIPLES "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;724;add_test;/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;0;")
add_test(ave_behavior_features_m3b "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_corpus/test_ave_behavior_features_m3b")
set_tests_properties(ave_behavior_features_m3b PROPERTIES  WORKING_DIRECTORY "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_corpus" _BACKTRACE_TRIPLES "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;731;add_test;/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;0;")
add_test(ave_behavior_gates "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_corpus/test_ave_behavior_gates")
set_tests_properties(ave_behavior_gates PROPERTIES  WORKING_DIRECTORY "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_corpus" _BACKTRACE_TRIPLES "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;735;add_test;/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;0;")
add_test(ave_behavior_m3b_python_parity "/usr/bin/python3" "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/scripts/behavior_encode_m3b.py")
set_tests_properties(ave_behavior_m3b_python_parity PROPERTIES  WORKING_DIRECTORY "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent" _BACKTRACE_TRIPLES "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;739;add_test;/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;0;")
add_test(ave_behavior_onnx_contract_check "bash" "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/scripts/check_behavior_onnx_contract.sh")
set_tests_properties(ave_behavior_onnx_contract_check PROPERTIES  WORKING_DIRECTORY "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent" _BACKTRACE_TRIPLES "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;746;add_test;/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;0;")
add_test(pmfe_scan_detail_format "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_corpus/test_pmfe_detail")
set_tests_properties(pmfe_scan_detail_format PROPERTIES  WORKING_DIRECTORY "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_corpus" _BACKTRACE_TRIPLES "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;756;add_test;/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;0;")
add_test(ave_file_fingerprint "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_corpus/test_ave_fp")
set_tests_properties(ave_file_fingerprint PROPERTIES  WORKING_DIRECTORY "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_corpus" _BACKTRACE_TRIPLES "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;1027;add_test;/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;0;")
add_test(ave_infer_dry_run "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_corpus/test_ave_infer")
set_tests_properties(ave_infer_dry_run PROPERTIES  WORKING_DIRECTORY "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_corpus" _BACKTRACE_TRIPLES "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;1028;add_test;/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;0;")
add_test(ave_phase1_contract "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_corpus/test_ave_phase1")
set_tests_properties(ave_phase1_contract PROPERTIES  WORKING_DIRECTORY "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_corpus" _BACKTRACE_TRIPLES "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;1029;add_test;/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;0;")
add_test(ave_static_features_lite512 "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_corpus/test_ave_static_features")
set_tests_properties(ave_static_features_lite512 PROPERTIES  WORKING_DIRECTORY "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_corpus" _BACKTRACE_TRIPLES "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;1032;add_test;/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;0;")
add_test(ave_sdk_smoke "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_corpus/test_ave_sdk")
set_tests_properties(ave_sdk_smoke PROPERTIES  WORKING_DIRECTORY "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_corpus" _BACKTRACE_TRIPLES "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;1033;add_test;/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;0;")
add_test(ave_fl_abi_c0 "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_corpus/test_ave_fl_abi")
set_tests_properties(ave_fl_abi_c0 PROPERTIES  WORKING_DIRECTORY "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_corpus" _BACKTRACE_TRIPLES "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;1034;add_test;/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;0;")
add_test(fl_ave_samples_bridge "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_corpus/test_fl_ave_samples_bridge")
set_tests_properties(fl_ave_samples_bridge PROPERTIES  WORKING_DIRECTORY "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_corpus" _BACKTRACE_TRIPLES "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;1036;add_test;/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;0;")
add_test(ave_suppression_sqlite "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_corpus/test_ave_suppression")
set_tests_properties(ave_suppression_sqlite PROPERTIES  WORKING_DIRECTORY "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_corpus" _BACKTRACE_TRIPLES "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;1038;add_test;/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;0;")
add_test(ave_scan_pipeline "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_corpus/test_ave_pipeline")
set_tests_properties(ave_scan_pipeline PROPERTIES  WORKING_DIRECTORY "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_corpus" _BACKTRACE_TRIPLES "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;1039;add_test;/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;0;")
add_test(config_fingerprint "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_corpus/test_config_fp")
set_tests_properties(config_fingerprint PROPERTIES  WORKING_DIRECTORY "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_corpus" _BACKTRACE_TRIPLES "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;1040;add_test;/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;0;")
add_test(shellcode_modules "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_corpus/test_shellcode")
set_tests_properties(shellcode_modules PROPERTIES  WORKING_DIRECTORY "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_corpus" _BACKTRACE_TRIPLES "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;1065;add_test;/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;0;")
add_test(shellcode_corpus "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_corpus/test_shellcode_corpus")
set_tests_properties(shellcode_corpus PROPERTIES  WORKING_DIRECTORY "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_corpus" _BACKTRACE_TRIPLES "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;1093;add_test;/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;0;")
add_test(edr_agent_smoke "bash" "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/scripts/agent_smoke.sh" "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_corpus/edr_agent")
set_tests_properties(edr_agent_smoke PROPERTIES  TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;1095;add_test;/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;0;")
