#include "edr/preprocess.h"
#include "edr/detection_decision.h"
#include "edr/dedup.h"
#include "edr/local_evidence_cache.h"
#include <stdatomic.h>
#include <string.h>

static _Atomic uint64_t s_baseline_rename_upload_skipped;

int edr_preprocess_admit_telemetry(const EdrBehaviorRecord *record,
                                  const EdrDetectionDecision *decision) {
  if (!record || !decision) return 0;
  /* Cache owns retention, aggregation and candidate attribution. Neither a
   * local-only decision nor duplicate transport is authority to skip it. */
  edr_local_evidence_cache_record_behavior(record);
  if (decision->drop || strcmp(decision->selection_action, "local_only") == 0)
    return 0;
  return edr_preprocess_should_emit(record);
}

int edr_preprocess_upload_admit(const EdrBehaviorRecord *record,
                               const EdrDetectionDecision *decision,
                               int p0_rules_ready, int local_forensics_dispatched) {
  if (!record || !decision || !p0_rules_ready || local_forensics_dispatched > 0 ||
      record->type != EDR_EVENT_FILE_RENAME ||
      !record->event_id[0] || !record->file_path[0] ||
      record->collector_evidence_gate[0] || record->cert_revoked_ancestor ||
      !decision->suppress || !decision->allowlisted_path ||
      decision->signal_reasons[0] || decision->has_remote ||
      decision->suspicious_parent || decision->context_correlated ||
      decision->persistence_change || decision->trigger_pmfe_scan ||
      decision->trigger_single_process_minidump ||
      strcmp(decision->selection_action, "emit_context") != 0 ||
      !strstr(decision->noise_reasons, "allowlisted_path")) {
    return 1;
  }

  /* The context is generated by detection_decision, not received from the
   * server. Missing fields fail open to upload when its schema changes. */
  const char *context = record->detection_context;
  static const char *const baseline_fields[] = {
      "\"ransom_behavior\":false", "\"ransom_canary\":false",
      "\"ransom_recovery_tamper\":false", "\"ransom_note\":false",
      "\"ransom_note_burst\":false", "\"security_product_kill\":false",
      "\"extension_changed\":false", "\"high_content_entropy\":false",
      "\"phase\":\"baseline\"", "\"kind\":\"\""};
  for (size_t i = 0u; i < sizeof(baseline_fields) / sizeof(baseline_fields[0]); i++) {
    if (!strstr(context, baseline_fields[i])) return 1;
  }
  atomic_fetch_add_explicit(&s_baseline_rename_upload_skipped, 1u,
                            memory_order_relaxed);
  return 0;
}

uint64_t edr_preprocess_baseline_rename_upload_skipped_count(void) {
  return atomic_load_explicit(&s_baseline_rename_upload_skipped,
                              memory_order_relaxed);
}
