/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "edr/v1/event.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif


/* The following messages exceed 64kB in size: edr_v1_BehaviorEvent */

/* The PB_FIELD_32BIT compilation option must be defined to support messages that exceed 64 kB in size. */
#ifndef PB_FIELD_32BIT
#error Enable PB_FIELD_32BIT to support messages exceeding 64kB in size: edr_v1_BehaviorEvent
#endif
PB_BIND(edr_v1_AveBehaviorEventFeed, edr_v1_AveBehaviorEventFeed, 4)


PB_BIND(edr_v1_BehaviorAlert, edr_v1_BehaviorAlert, 2)


PB_BIND(edr_v1_BehaviorEvent, edr_v1_BehaviorEvent, 4)


PB_BIND(edr_v1_ProcessDetail, edr_v1_ProcessDetail, 4)


PB_BIND(edr_v1_FileDetail, edr_v1_FileDetail, 4)


PB_BIND(edr_v1_RegistryDetail, edr_v1_RegistryDetail, 4)


PB_BIND(edr_v1_NetworkDetail, edr_v1_NetworkDetail, 4)


PB_BIND(edr_v1_DnsDetail, edr_v1_DnsDetail, 2)


PB_BIND(edr_v1_ScriptDetail, edr_v1_ScriptDetail, 4)


PB_BIND(edr_v1_ProcessContext, edr_v1_ProcessContext, 4)
