# CMake generated Testfile for 
# Source directory: /Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent
# Build directory: /Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_fl3
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(edr_agent_help "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_fl3/edr_agent" "--help")
set_tests_properties(edr_agent_help PROPERTIES  _BACKTRACE_TRIPLES "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;409;add_test;/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;0;")
add_test(pmfe_scan_detail_format "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_fl3/test_pmfe_detail")
set_tests_properties(pmfe_scan_detail_format PROPERTIES  WORKING_DIRECTORY "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_fl3" _BACKTRACE_TRIPLES "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;521;add_test;/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;0;")
add_test(fl_crypto_fl3 "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_fl3/test_fl_crypto_fl3")
set_tests_properties(fl_crypto_fl3 PROPERTIES  WORKING_DIRECTORY "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_fl3" _BACKTRACE_TRIPLES "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;586;add_test;/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;0;")
add_test(fl_pb_gradient_chunk "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_fl3/test_fl_pb_gradient_chunk")
set_tests_properties(fl_pb_gradient_chunk PROPERTIES  WORKING_DIRECTORY "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_fl3" _BACKTRACE_TRIPLES "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;590;add_test;/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;0;")
add_test(ave_file_fingerprint "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_fl3/test_ave_fp")
set_tests_properties(ave_file_fingerprint PROPERTIES  WORKING_DIRECTORY "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_fl3" _BACKTRACE_TRIPLES "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;734;add_test;/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;0;")
add_test(ave_infer_dry_run "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_fl3/test_ave_infer")
set_tests_properties(ave_infer_dry_run PROPERTIES  WORKING_DIRECTORY "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_fl3" _BACKTRACE_TRIPLES "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;735;add_test;/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;0;")
add_test(ave_phase1_contract "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_fl3/test_ave_phase1")
set_tests_properties(ave_phase1_contract PROPERTIES  WORKING_DIRECTORY "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_fl3" _BACKTRACE_TRIPLES "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;736;add_test;/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;0;")
add_test(ave_static_features_lite512 "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_fl3/test_ave_static_features")
set_tests_properties(ave_static_features_lite512 PROPERTIES  WORKING_DIRECTORY "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_fl3" _BACKTRACE_TRIPLES "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;739;add_test;/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;0;")
add_test(ave_sdk_smoke "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_fl3/test_ave_sdk")
set_tests_properties(ave_sdk_smoke PROPERTIES  WORKING_DIRECTORY "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_fl3" _BACKTRACE_TRIPLES "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;740;add_test;/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;0;")
add_test(ave_fl_abi_c0 "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_fl3/test_ave_fl_abi")
set_tests_properties(ave_fl_abi_c0 PROPERTIES  WORKING_DIRECTORY "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_fl3" _BACKTRACE_TRIPLES "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;741;add_test;/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;0;")
add_test(ave_suppression_sqlite "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_fl3/test_ave_suppression")
set_tests_properties(ave_suppression_sqlite PROPERTIES  WORKING_DIRECTORY "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_fl3" _BACKTRACE_TRIPLES "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;742;add_test;/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;0;")
add_test(ave_scan_pipeline "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_fl3/test_ave_pipeline")
set_tests_properties(ave_scan_pipeline PROPERTIES  WORKING_DIRECTORY "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_fl3" _BACKTRACE_TRIPLES "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;743;add_test;/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;0;")
add_test(config_fingerprint "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_fl3/test_config_fp")
set_tests_properties(config_fingerprint PROPERTIES  WORKING_DIRECTORY "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_fl3" _BACKTRACE_TRIPLES "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;744;add_test;/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;0;")
add_test(fl_trainer_c1 "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_fl3/test_fl_trainer_smoke")
set_tests_properties(fl_trainer_c1 PROPERTIES  WORKING_DIRECTORY "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_fl3" _BACKTRACE_TRIPLES "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;746;add_test;/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;0;")
add_test(shellcode_modules "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_fl3/test_shellcode")
set_tests_properties(shellcode_modules PROPERTIES  WORKING_DIRECTORY "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_fl3" _BACKTRACE_TRIPLES "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;769;add_test;/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;0;")
add_test(edr_agent_smoke "bash" "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/scripts/agent_smoke.sh" "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/build_fl3/edr_agent")
set_tests_properties(edr_agent_smoke PROPERTIES  TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;770;add_test;/Users/qiuxinliang/工程区/EDR DEV/AI Agent/edr-agent/CMakeLists.txt;0;")
