// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: edr/v1/ingest.proto

#include "edr/v1/ingest.pb.h"
#include "edr/v1/ingest.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace edr {
namespace v1 {

static const char* EventIngest_method_names[] = {
  "/edr.v1.EventIngest/ReportEvents",
  "/edr.v1.EventIngest/Subscribe",
  "/edr.v1.EventIngest/ReportCommandResult",
  "/edr.v1.EventIngest/UploadFile",
};

std::unique_ptr< EventIngest::Stub> EventIngest::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< EventIngest::Stub> stub(new EventIngest::Stub(channel, options));
  return stub;
}

EventIngest::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ReportEvents_(EventIngest_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Subscribe_(EventIngest_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_ReportCommandResult_(EventIngest_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UploadFile_(EventIngest_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  {}

::grpc::Status EventIngest::Stub::ReportEvents(::grpc::ClientContext* context, const ::edr::v1::ReportEventsRequest& request, ::edr::v1::ReportEventsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::edr::v1::ReportEventsRequest, ::edr::v1::ReportEventsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReportEvents_, context, request, response);
}

void EventIngest::Stub::async::ReportEvents(::grpc::ClientContext* context, const ::edr::v1::ReportEventsRequest* request, ::edr::v1::ReportEventsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::edr::v1::ReportEventsRequest, ::edr::v1::ReportEventsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReportEvents_, context, request, response, std::move(f));
}

void EventIngest::Stub::async::ReportEvents(::grpc::ClientContext* context, const ::edr::v1::ReportEventsRequest* request, ::edr::v1::ReportEventsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReportEvents_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::edr::v1::ReportEventsResponse>* EventIngest::Stub::PrepareAsyncReportEventsRaw(::grpc::ClientContext* context, const ::edr::v1::ReportEventsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::edr::v1::ReportEventsResponse, ::edr::v1::ReportEventsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReportEvents_, context, request);
}

::grpc::ClientAsyncResponseReader< ::edr::v1::ReportEventsResponse>* EventIngest::Stub::AsyncReportEventsRaw(::grpc::ClientContext* context, const ::edr::v1::ReportEventsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReportEventsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::edr::v1::CommandEnvelope>* EventIngest::Stub::SubscribeRaw(::grpc::ClientContext* context, const ::edr::v1::SubscribeRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::edr::v1::CommandEnvelope>::Create(channel_.get(), rpcmethod_Subscribe_, context, request);
}

void EventIngest::Stub::async::Subscribe(::grpc::ClientContext* context, const ::edr::v1::SubscribeRequest* request, ::grpc::ClientReadReactor< ::edr::v1::CommandEnvelope>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::edr::v1::CommandEnvelope>::Create(stub_->channel_.get(), stub_->rpcmethod_Subscribe_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::edr::v1::CommandEnvelope>* EventIngest::Stub::AsyncSubscribeRaw(::grpc::ClientContext* context, const ::edr::v1::SubscribeRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::edr::v1::CommandEnvelope>::Create(channel_.get(), cq, rpcmethod_Subscribe_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::edr::v1::CommandEnvelope>* EventIngest::Stub::PrepareAsyncSubscribeRaw(::grpc::ClientContext* context, const ::edr::v1::SubscribeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::edr::v1::CommandEnvelope>::Create(channel_.get(), cq, rpcmethod_Subscribe_, context, request, false, nullptr);
}

::grpc::Status EventIngest::Stub::ReportCommandResult(::grpc::ClientContext* context, const ::edr::v1::ReportCommandResultRequest& request, ::edr::v1::ReportCommandResultResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::edr::v1::ReportCommandResultRequest, ::edr::v1::ReportCommandResultResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReportCommandResult_, context, request, response);
}

void EventIngest::Stub::async::ReportCommandResult(::grpc::ClientContext* context, const ::edr::v1::ReportCommandResultRequest* request, ::edr::v1::ReportCommandResultResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::edr::v1::ReportCommandResultRequest, ::edr::v1::ReportCommandResultResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReportCommandResult_, context, request, response, std::move(f));
}

void EventIngest::Stub::async::ReportCommandResult(::grpc::ClientContext* context, const ::edr::v1::ReportCommandResultRequest* request, ::edr::v1::ReportCommandResultResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReportCommandResult_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::edr::v1::ReportCommandResultResponse>* EventIngest::Stub::PrepareAsyncReportCommandResultRaw(::grpc::ClientContext* context, const ::edr::v1::ReportCommandResultRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::edr::v1::ReportCommandResultResponse, ::edr::v1::ReportCommandResultRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReportCommandResult_, context, request);
}

::grpc::ClientAsyncResponseReader< ::edr::v1::ReportCommandResultResponse>* EventIngest::Stub::AsyncReportCommandResultRaw(::grpc::ClientContext* context, const ::edr::v1::ReportCommandResultRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReportCommandResultRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientWriter< ::edr::v1::FileChunk>* EventIngest::Stub::UploadFileRaw(::grpc::ClientContext* context, ::edr::v1::UploadResult* response) {
  return ::grpc::internal::ClientWriterFactory< ::edr::v1::FileChunk>::Create(channel_.get(), rpcmethod_UploadFile_, context, response);
}

void EventIngest::Stub::async::UploadFile(::grpc::ClientContext* context, ::edr::v1::UploadResult* response, ::grpc::ClientWriteReactor< ::edr::v1::FileChunk>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::edr::v1::FileChunk>::Create(stub_->channel_.get(), stub_->rpcmethod_UploadFile_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::edr::v1::FileChunk>* EventIngest::Stub::AsyncUploadFileRaw(::grpc::ClientContext* context, ::edr::v1::UploadResult* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::edr::v1::FileChunk>::Create(channel_.get(), cq, rpcmethod_UploadFile_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::edr::v1::FileChunk>* EventIngest::Stub::PrepareAsyncUploadFileRaw(::grpc::ClientContext* context, ::edr::v1::UploadResult* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::edr::v1::FileChunk>::Create(channel_.get(), cq, rpcmethod_UploadFile_, context, response, false, nullptr);
}

EventIngest::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EventIngest_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EventIngest::Service, ::edr::v1::ReportEventsRequest, ::edr::v1::ReportEventsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EventIngest::Service* service,
             ::grpc::ServerContext* ctx,
             const ::edr::v1::ReportEventsRequest* req,
             ::edr::v1::ReportEventsResponse* resp) {
               return service->ReportEvents(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EventIngest_method_names[1],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< EventIngest::Service, ::edr::v1::SubscribeRequest, ::edr::v1::CommandEnvelope>(
          [](EventIngest::Service* service,
             ::grpc::ServerContext* ctx,
             const ::edr::v1::SubscribeRequest* req,
             ::grpc::ServerWriter<::edr::v1::CommandEnvelope>* writer) {
               return service->Subscribe(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EventIngest_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EventIngest::Service, ::edr::v1::ReportCommandResultRequest, ::edr::v1::ReportCommandResultResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EventIngest::Service* service,
             ::grpc::ServerContext* ctx,
             const ::edr::v1::ReportCommandResultRequest* req,
             ::edr::v1::ReportCommandResultResponse* resp) {
               return service->ReportCommandResult(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EventIngest_method_names[3],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< EventIngest::Service, ::edr::v1::FileChunk, ::edr::v1::UploadResult>(
          [](EventIngest::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReader<::edr::v1::FileChunk>* reader,
             ::edr::v1::UploadResult* resp) {
               return service->UploadFile(ctx, reader, resp);
             }, this)));
}

EventIngest::Service::~Service() {
}

::grpc::Status EventIngest::Service::ReportEvents(::grpc::ServerContext* context, const ::edr::v1::ReportEventsRequest* request, ::edr::v1::ReportEventsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EventIngest::Service::Subscribe(::grpc::ServerContext* context, const ::edr::v1::SubscribeRequest* request, ::grpc::ServerWriter< ::edr::v1::CommandEnvelope>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EventIngest::Service::ReportCommandResult(::grpc::ServerContext* context, const ::edr::v1::ReportCommandResultRequest* request, ::edr::v1::ReportCommandResultResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EventIngest::Service::UploadFile(::grpc::ServerContext* context, ::grpc::ServerReader< ::edr::v1::FileChunk>* reader, ::edr::v1::UploadResult* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace edr
}  // namespace v1
#include <grpcpp/ports_undef.inc>

