// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: edr/v1/ingest.proto
// Original file comments:
// §7 gRPC 上报 / 指令订阅 — 与服务端 EventIngest 对齐
// SOAR：编排侧通过 CommandEnvelope 扩展字段关联 playbook；执行结果经 ReportCommandResult 回传对账。
#ifndef GRPC_edr_2fv1_2fingest_2eproto__INCLUDED
#define GRPC_edr_2fv1_2fingest_2eproto__INCLUDED

#include "edr/v1/ingest.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace edr {
namespace v1 {

class EventIngest final {
 public:
  static constexpr char const* service_full_name() {
    return "edr.v1.EventIngest";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status ReportEvents(::grpc::ClientContext* context, const ::edr::v1::ReportEventsRequest& request, ::edr::v1::ReportEventsResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::edr::v1::ReportEventsResponse>> AsyncReportEvents(::grpc::ClientContext* context, const ::edr::v1::ReportEventsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::edr::v1::ReportEventsResponse>>(AsyncReportEventsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::edr::v1::ReportEventsResponse>> PrepareAsyncReportEvents(::grpc::ClientContext* context, const ::edr::v1::ReportEventsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::edr::v1::ReportEventsResponse>>(PrepareAsyncReportEventsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderInterface< ::edr::v1::CommandEnvelope>> Subscribe(::grpc::ClientContext* context, const ::edr::v1::SubscribeRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::edr::v1::CommandEnvelope>>(SubscribeRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::edr::v1::CommandEnvelope>> AsyncSubscribe(::grpc::ClientContext* context, const ::edr::v1::SubscribeRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::edr::v1::CommandEnvelope>>(AsyncSubscribeRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::edr::v1::CommandEnvelope>> PrepareAsyncSubscribe(::grpc::ClientContext* context, const ::edr::v1::SubscribeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::edr::v1::CommandEnvelope>>(PrepareAsyncSubscribeRaw(context, request, cq));
    }
    virtual ::grpc::Status ReportCommandResult(::grpc::ClientContext* context, const ::edr::v1::ReportCommandResultRequest& request, ::edr::v1::ReportCommandResultResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::edr::v1::ReportCommandResultResponse>> AsyncReportCommandResult(::grpc::ClientContext* context, const ::edr::v1::ReportCommandResultRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::edr::v1::ReportCommandResultResponse>>(AsyncReportCommandResultRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::edr::v1::ReportCommandResultResponse>> PrepareAsyncReportCommandResult(::grpc::ClientContext* context, const ::edr::v1::ReportCommandResultRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::edr::v1::ReportCommandResultResponse>>(PrepareAsyncReportCommandResultRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientWriterInterface< ::edr::v1::FileChunk>> UploadFile(::grpc::ClientContext* context, ::edr::v1::UploadResult* response) {
      return std::unique_ptr< ::grpc::ClientWriterInterface< ::edr::v1::FileChunk>>(UploadFileRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::edr::v1::FileChunk>> AsyncUploadFile(::grpc::ClientContext* context, ::edr::v1::UploadResult* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::edr::v1::FileChunk>>(AsyncUploadFileRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::edr::v1::FileChunk>> PrepareAsyncUploadFile(::grpc::ClientContext* context, ::edr::v1::UploadResult* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::edr::v1::FileChunk>>(PrepareAsyncUploadFileRaw(context, response, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void ReportEvents(::grpc::ClientContext* context, const ::edr::v1::ReportEventsRequest* request, ::edr::v1::ReportEventsResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ReportEvents(::grpc::ClientContext* context, const ::edr::v1::ReportEventsRequest* request, ::edr::v1::ReportEventsResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void Subscribe(::grpc::ClientContext* context, const ::edr::v1::SubscribeRequest* request, ::grpc::ClientReadReactor< ::edr::v1::CommandEnvelope>* reactor) = 0;
      virtual void ReportCommandResult(::grpc::ClientContext* context, const ::edr::v1::ReportCommandResultRequest* request, ::edr::v1::ReportCommandResultResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ReportCommandResult(::grpc::ClientContext* context, const ::edr::v1::ReportCommandResultRequest* request, ::edr::v1::ReportCommandResultResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void UploadFile(::grpc::ClientContext* context, ::edr::v1::UploadResult* response, ::grpc::ClientWriteReactor< ::edr::v1::FileChunk>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::edr::v1::ReportEventsResponse>* AsyncReportEventsRaw(::grpc::ClientContext* context, const ::edr::v1::ReportEventsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::edr::v1::ReportEventsResponse>* PrepareAsyncReportEventsRaw(::grpc::ClientContext* context, const ::edr::v1::ReportEventsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::edr::v1::CommandEnvelope>* SubscribeRaw(::grpc::ClientContext* context, const ::edr::v1::SubscribeRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::edr::v1::CommandEnvelope>* AsyncSubscribeRaw(::grpc::ClientContext* context, const ::edr::v1::SubscribeRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::edr::v1::CommandEnvelope>* PrepareAsyncSubscribeRaw(::grpc::ClientContext* context, const ::edr::v1::SubscribeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::edr::v1::ReportCommandResultResponse>* AsyncReportCommandResultRaw(::grpc::ClientContext* context, const ::edr::v1::ReportCommandResultRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::edr::v1::ReportCommandResultResponse>* PrepareAsyncReportCommandResultRaw(::grpc::ClientContext* context, const ::edr::v1::ReportCommandResultRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientWriterInterface< ::edr::v1::FileChunk>* UploadFileRaw(::grpc::ClientContext* context, ::edr::v1::UploadResult* response) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::edr::v1::FileChunk>* AsyncUploadFileRaw(::grpc::ClientContext* context, ::edr::v1::UploadResult* response, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::edr::v1::FileChunk>* PrepareAsyncUploadFileRaw(::grpc::ClientContext* context, ::edr::v1::UploadResult* response, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status ReportEvents(::grpc::ClientContext* context, const ::edr::v1::ReportEventsRequest& request, ::edr::v1::ReportEventsResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::edr::v1::ReportEventsResponse>> AsyncReportEvents(::grpc::ClientContext* context, const ::edr::v1::ReportEventsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::edr::v1::ReportEventsResponse>>(AsyncReportEventsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::edr::v1::ReportEventsResponse>> PrepareAsyncReportEvents(::grpc::ClientContext* context, const ::edr::v1::ReportEventsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::edr::v1::ReportEventsResponse>>(PrepareAsyncReportEventsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::edr::v1::CommandEnvelope>> Subscribe(::grpc::ClientContext* context, const ::edr::v1::SubscribeRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::edr::v1::CommandEnvelope>>(SubscribeRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::edr::v1::CommandEnvelope>> AsyncSubscribe(::grpc::ClientContext* context, const ::edr::v1::SubscribeRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::edr::v1::CommandEnvelope>>(AsyncSubscribeRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::edr::v1::CommandEnvelope>> PrepareAsyncSubscribe(::grpc::ClientContext* context, const ::edr::v1::SubscribeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::edr::v1::CommandEnvelope>>(PrepareAsyncSubscribeRaw(context, request, cq));
    }
    ::grpc::Status ReportCommandResult(::grpc::ClientContext* context, const ::edr::v1::ReportCommandResultRequest& request, ::edr::v1::ReportCommandResultResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::edr::v1::ReportCommandResultResponse>> AsyncReportCommandResult(::grpc::ClientContext* context, const ::edr::v1::ReportCommandResultRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::edr::v1::ReportCommandResultResponse>>(AsyncReportCommandResultRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::edr::v1::ReportCommandResultResponse>> PrepareAsyncReportCommandResult(::grpc::ClientContext* context, const ::edr::v1::ReportCommandResultRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::edr::v1::ReportCommandResultResponse>>(PrepareAsyncReportCommandResultRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientWriter< ::edr::v1::FileChunk>> UploadFile(::grpc::ClientContext* context, ::edr::v1::UploadResult* response) {
      return std::unique_ptr< ::grpc::ClientWriter< ::edr::v1::FileChunk>>(UploadFileRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::edr::v1::FileChunk>> AsyncUploadFile(::grpc::ClientContext* context, ::edr::v1::UploadResult* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::edr::v1::FileChunk>>(AsyncUploadFileRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::edr::v1::FileChunk>> PrepareAsyncUploadFile(::grpc::ClientContext* context, ::edr::v1::UploadResult* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::edr::v1::FileChunk>>(PrepareAsyncUploadFileRaw(context, response, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ReportEvents(::grpc::ClientContext* context, const ::edr::v1::ReportEventsRequest* request, ::edr::v1::ReportEventsResponse* response, std::function<void(::grpc::Status)>) override;
      void ReportEvents(::grpc::ClientContext* context, const ::edr::v1::ReportEventsRequest* request, ::edr::v1::ReportEventsResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Subscribe(::grpc::ClientContext* context, const ::edr::v1::SubscribeRequest* request, ::grpc::ClientReadReactor< ::edr::v1::CommandEnvelope>* reactor) override;
      void ReportCommandResult(::grpc::ClientContext* context, const ::edr::v1::ReportCommandResultRequest* request, ::edr::v1::ReportCommandResultResponse* response, std::function<void(::grpc::Status)>) override;
      void ReportCommandResult(::grpc::ClientContext* context, const ::edr::v1::ReportCommandResultRequest* request, ::edr::v1::ReportCommandResultResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void UploadFile(::grpc::ClientContext* context, ::edr::v1::UploadResult* response, ::grpc::ClientWriteReactor< ::edr::v1::FileChunk>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::edr::v1::ReportEventsResponse>* AsyncReportEventsRaw(::grpc::ClientContext* context, const ::edr::v1::ReportEventsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::edr::v1::ReportEventsResponse>* PrepareAsyncReportEventsRaw(::grpc::ClientContext* context, const ::edr::v1::ReportEventsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::edr::v1::CommandEnvelope>* SubscribeRaw(::grpc::ClientContext* context, const ::edr::v1::SubscribeRequest& request) override;
    ::grpc::ClientAsyncReader< ::edr::v1::CommandEnvelope>* AsyncSubscribeRaw(::grpc::ClientContext* context, const ::edr::v1::SubscribeRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::edr::v1::CommandEnvelope>* PrepareAsyncSubscribeRaw(::grpc::ClientContext* context, const ::edr::v1::SubscribeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::edr::v1::ReportCommandResultResponse>* AsyncReportCommandResultRaw(::grpc::ClientContext* context, const ::edr::v1::ReportCommandResultRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::edr::v1::ReportCommandResultResponse>* PrepareAsyncReportCommandResultRaw(::grpc::ClientContext* context, const ::edr::v1::ReportCommandResultRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientWriter< ::edr::v1::FileChunk>* UploadFileRaw(::grpc::ClientContext* context, ::edr::v1::UploadResult* response) override;
    ::grpc::ClientAsyncWriter< ::edr::v1::FileChunk>* AsyncUploadFileRaw(::grpc::ClientContext* context, ::edr::v1::UploadResult* response, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncWriter< ::edr::v1::FileChunk>* PrepareAsyncUploadFileRaw(::grpc::ClientContext* context, ::edr::v1::UploadResult* response, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ReportEvents_;
    const ::grpc::internal::RpcMethod rpcmethod_Subscribe_;
    const ::grpc::internal::RpcMethod rpcmethod_ReportCommandResult_;
    const ::grpc::internal::RpcMethod rpcmethod_UploadFile_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status ReportEvents(::grpc::ServerContext* context, const ::edr::v1::ReportEventsRequest* request, ::edr::v1::ReportEventsResponse* response);
    virtual ::grpc::Status Subscribe(::grpc::ServerContext* context, const ::edr::v1::SubscribeRequest* request, ::grpc::ServerWriter< ::edr::v1::CommandEnvelope>* writer);
    virtual ::grpc::Status ReportCommandResult(::grpc::ServerContext* context, const ::edr::v1::ReportCommandResultRequest* request, ::edr::v1::ReportCommandResultResponse* response);
    virtual ::grpc::Status UploadFile(::grpc::ServerContext* context, ::grpc::ServerReader< ::edr::v1::FileChunk>* reader, ::edr::v1::UploadResult* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ReportEvents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ReportEvents() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ReportEvents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportEvents(::grpc::ServerContext* /*context*/, const ::edr::v1::ReportEventsRequest* /*request*/, ::edr::v1::ReportEventsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReportEvents(::grpc::ServerContext* context, ::edr::v1::ReportEventsRequest* request, ::grpc::ServerAsyncResponseWriter< ::edr::v1::ReportEventsResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Subscribe : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Subscribe() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Subscribe() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Subscribe(::grpc::ServerContext* /*context*/, const ::edr::v1::SubscribeRequest* /*request*/, ::grpc::ServerWriter< ::edr::v1::CommandEnvelope>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSubscribe(::grpc::ServerContext* context, ::edr::v1::SubscribeRequest* request, ::grpc::ServerAsyncWriter< ::edr::v1::CommandEnvelope>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ReportCommandResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ReportCommandResult() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_ReportCommandResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportCommandResult(::grpc::ServerContext* /*context*/, const ::edr::v1::ReportCommandResultRequest* /*request*/, ::edr::v1::ReportCommandResultResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReportCommandResult(::grpc::ServerContext* context, ::edr::v1::ReportCommandResultRequest* request, ::grpc::ServerAsyncResponseWriter< ::edr::v1::ReportCommandResultResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_UploadFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_UploadFile() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_UploadFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UploadFile(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::edr::v1::FileChunk>* /*reader*/, ::edr::v1::UploadResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUploadFile(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::edr::v1::UploadResult, ::edr::v1::FileChunk>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(3, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ReportEvents<WithAsyncMethod_Subscribe<WithAsyncMethod_ReportCommandResult<WithAsyncMethod_UploadFile<Service > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ReportEvents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ReportEvents() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::edr::v1::ReportEventsRequest, ::edr::v1::ReportEventsResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::edr::v1::ReportEventsRequest* request, ::edr::v1::ReportEventsResponse* response) { return this->ReportEvents(context, request, response); }));}
    void SetMessageAllocatorFor_ReportEvents(
        ::grpc::MessageAllocator< ::edr::v1::ReportEventsRequest, ::edr::v1::ReportEventsResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::edr::v1::ReportEventsRequest, ::edr::v1::ReportEventsResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ReportEvents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportEvents(::grpc::ServerContext* /*context*/, const ::edr::v1::ReportEventsRequest* /*request*/, ::edr::v1::ReportEventsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReportEvents(
      ::grpc::CallbackServerContext* /*context*/, const ::edr::v1::ReportEventsRequest* /*request*/, ::edr::v1::ReportEventsResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Subscribe : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Subscribe() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackServerStreamingHandler< ::edr::v1::SubscribeRequest, ::edr::v1::CommandEnvelope>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::edr::v1::SubscribeRequest* request) { return this->Subscribe(context, request); }));
    }
    ~WithCallbackMethod_Subscribe() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Subscribe(::grpc::ServerContext* /*context*/, const ::edr::v1::SubscribeRequest* /*request*/, ::grpc::ServerWriter< ::edr::v1::CommandEnvelope>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::edr::v1::CommandEnvelope>* Subscribe(
      ::grpc::CallbackServerContext* /*context*/, const ::edr::v1::SubscribeRequest* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ReportCommandResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ReportCommandResult() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::edr::v1::ReportCommandResultRequest, ::edr::v1::ReportCommandResultResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::edr::v1::ReportCommandResultRequest* request, ::edr::v1::ReportCommandResultResponse* response) { return this->ReportCommandResult(context, request, response); }));}
    void SetMessageAllocatorFor_ReportCommandResult(
        ::grpc::MessageAllocator< ::edr::v1::ReportCommandResultRequest, ::edr::v1::ReportCommandResultResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::edr::v1::ReportCommandResultRequest, ::edr::v1::ReportCommandResultResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ReportCommandResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportCommandResult(::grpc::ServerContext* /*context*/, const ::edr::v1::ReportCommandResultRequest* /*request*/, ::edr::v1::ReportCommandResultResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReportCommandResult(
      ::grpc::CallbackServerContext* /*context*/, const ::edr::v1::ReportCommandResultRequest* /*request*/, ::edr::v1::ReportCommandResultResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_UploadFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_UploadFile() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackClientStreamingHandler< ::edr::v1::FileChunk, ::edr::v1::UploadResult>(
            [this](
                   ::grpc::CallbackServerContext* context, ::edr::v1::UploadResult* response) { return this->UploadFile(context, response); }));
    }
    ~WithCallbackMethod_UploadFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UploadFile(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::edr::v1::FileChunk>* /*reader*/, ::edr::v1::UploadResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::edr::v1::FileChunk>* UploadFile(
      ::grpc::CallbackServerContext* /*context*/, ::edr::v1::UploadResult* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_ReportEvents<WithCallbackMethod_Subscribe<WithCallbackMethod_ReportCommandResult<WithCallbackMethod_UploadFile<Service > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ReportEvents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ReportEvents() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ReportEvents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportEvents(::grpc::ServerContext* /*context*/, const ::edr::v1::ReportEventsRequest* /*request*/, ::edr::v1::ReportEventsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Subscribe : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Subscribe() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Subscribe() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Subscribe(::grpc::ServerContext* /*context*/, const ::edr::v1::SubscribeRequest* /*request*/, ::grpc::ServerWriter< ::edr::v1::CommandEnvelope>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ReportCommandResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ReportCommandResult() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_ReportCommandResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportCommandResult(::grpc::ServerContext* /*context*/, const ::edr::v1::ReportCommandResultRequest* /*request*/, ::edr::v1::ReportCommandResultResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_UploadFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_UploadFile() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_UploadFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UploadFile(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::edr::v1::FileChunk>* /*reader*/, ::edr::v1::UploadResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ReportEvents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ReportEvents() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ReportEvents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportEvents(::grpc::ServerContext* /*context*/, const ::edr::v1::ReportEventsRequest* /*request*/, ::edr::v1::ReportEventsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReportEvents(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Subscribe : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Subscribe() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_Subscribe() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Subscribe(::grpc::ServerContext* /*context*/, const ::edr::v1::SubscribeRequest* /*request*/, ::grpc::ServerWriter< ::edr::v1::CommandEnvelope>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSubscribe(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ReportCommandResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ReportCommandResult() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_ReportCommandResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportCommandResult(::grpc::ServerContext* /*context*/, const ::edr::v1::ReportCommandResultRequest* /*request*/, ::edr::v1::ReportCommandResultResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReportCommandResult(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_UploadFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_UploadFile() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_UploadFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UploadFile(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::edr::v1::FileChunk>* /*reader*/, ::edr::v1::UploadResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUploadFile(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(3, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ReportEvents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ReportEvents() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ReportEvents(context, request, response); }));
    }
    ~WithRawCallbackMethod_ReportEvents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportEvents(::grpc::ServerContext* /*context*/, const ::edr::v1::ReportEventsRequest* /*request*/, ::edr::v1::ReportEventsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReportEvents(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Subscribe : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Subscribe() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->Subscribe(context, request); }));
    }
    ~WithRawCallbackMethod_Subscribe() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Subscribe(::grpc::ServerContext* /*context*/, const ::edr::v1::SubscribeRequest* /*request*/, ::grpc::ServerWriter< ::edr::v1::CommandEnvelope>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* Subscribe(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ReportCommandResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ReportCommandResult() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ReportCommandResult(context, request, response); }));
    }
    ~WithRawCallbackMethod_ReportCommandResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportCommandResult(::grpc::ServerContext* /*context*/, const ::edr::v1::ReportCommandResultRequest* /*request*/, ::edr::v1::ReportCommandResultResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReportCommandResult(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_UploadFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_UploadFile() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackClientStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, ::grpc::ByteBuffer* response) { return this->UploadFile(context, response); }));
    }
    ~WithRawCallbackMethod_UploadFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UploadFile(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::edr::v1::FileChunk>* /*reader*/, ::edr::v1::UploadResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::grpc::ByteBuffer>* UploadFile(
      ::grpc::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ReportEvents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ReportEvents() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::edr::v1::ReportEventsRequest, ::edr::v1::ReportEventsResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::edr::v1::ReportEventsRequest, ::edr::v1::ReportEventsResponse>* streamer) {
                       return this->StreamedReportEvents(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ReportEvents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ReportEvents(::grpc::ServerContext* /*context*/, const ::edr::v1::ReportEventsRequest* /*request*/, ::edr::v1::ReportEventsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedReportEvents(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::edr::v1::ReportEventsRequest,::edr::v1::ReportEventsResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ReportCommandResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ReportCommandResult() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::edr::v1::ReportCommandResultRequest, ::edr::v1::ReportCommandResultResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::edr::v1::ReportCommandResultRequest, ::edr::v1::ReportCommandResultResponse>* streamer) {
                       return this->StreamedReportCommandResult(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ReportCommandResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ReportCommandResult(::grpc::ServerContext* /*context*/, const ::edr::v1::ReportCommandResultRequest* /*request*/, ::edr::v1::ReportCommandResultResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedReportCommandResult(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::edr::v1::ReportCommandResultRequest,::edr::v1::ReportCommandResultResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ReportEvents<WithStreamedUnaryMethod_ReportCommandResult<Service > > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_Subscribe : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_Subscribe() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::edr::v1::SubscribeRequest, ::edr::v1::CommandEnvelope>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::edr::v1::SubscribeRequest, ::edr::v1::CommandEnvelope>* streamer) {
                       return this->StreamedSubscribe(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_Subscribe() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Subscribe(::grpc::ServerContext* /*context*/, const ::edr::v1::SubscribeRequest* /*request*/, ::grpc::ServerWriter< ::edr::v1::CommandEnvelope>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedSubscribe(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::edr::v1::SubscribeRequest,::edr::v1::CommandEnvelope>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_Subscribe<Service > SplitStreamedService;
  typedef WithStreamedUnaryMethod_ReportEvents<WithSplitStreamingMethod_Subscribe<WithStreamedUnaryMethod_ReportCommandResult<Service > > > StreamedService;
};

}  // namespace v1
}  // namespace edr


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_edr_2fv1_2fingest_2eproto__INCLUDED
