#Requires -Version 5.1
<#
.SYNOPSIS
  独立运行：调用 POST /api/v1/enroll，生成 agent.toml（不依赖 Python）。

.DESCRIPTION
  环境变量（必填）：
    EDR_API_BASE      平台 REST 根，如 http://127.0.0.1:8080
    EDR_ENROLL_TOKEN  注册 Token

  可选：
    EDR_OUTPUT              输出路径，默认当前目录下的 agent.toml（相对路径相对「执行脚本时的当前目录」）
    EDR_AGENT_VERSION       默认 0.3.0
    EDR_OVERRIDE_SERVER_ADDR
    EDR_INSECURE_TLS=1      [System.Net.ServicePointManager]::ServerCertificateValidationCallback（仅调试）

.EXAMPLE
  $env:EDR_API_BASE="http://127.0.0.1:8080"
  $env:EDR_ENROLL_TOKEN="xxxxxxxx"
  .\edr_agent_install.ps1 -Output "C:\Program Files\EDR Agent\agent.toml"
#>
param(
  [string]$Output = $(if ($env:EDR_OUTPUT) { $env:EDR_OUTPUT } else { "agent.toml" }),
  [switch]$DryRun
)

$ErrorActionPreference = "Stop"

function Get-EnrollOs {
  if ($env:OS -match "Windows_NT" -or $env:OS -like "*Windows*") { return "windows" }
  if ($IsMacOS) { return "darwin" }
  return "linux"
}

$api = $env:EDR_API_BASE
$tok = $env:EDR_ENROLL_TOKEN
if (-not $api -or -not $tok) {
  Write-Error "Set EDR_API_BASE and EDR_ENROLL_TOKEN"
}

$api = $api.TrimEnd("/")
$uri = "$api/api/v1/enroll"
$av = if ($env:EDR_AGENT_VERSION) { $env:EDR_AGENT_VERSION } else { "0.3.0" }

$bodyObj = @{
  token         = $tok
  hostname      = $env:COMPUTERNAME
  os            = (Get-EnrollOs)
  arch          = $env:PROCESSOR_ARCHITECTURE
  agent_version = $av
  ip            = ""
}
$json = $bodyObj | ConvertTo-Json -Compress

if ($env:EDR_INSECURE_TLS -eq "1") {
  if (-not ([System.Management.Automation.PSTypeName]'TrustAllCertsPolicy').Type) {
    Add-Type @"
using System.Net;
using System.Security.Cryptography.X509Certificates;
public class TrustAllCertsPolicy : ICertificatePolicy {
  public bool CheckValidationResult(ServicePoint sp, X509Certificate cert, WebRequest req, int problem) { return true; }
}
"@
  }
  [System.Net.ServicePointManager]::CertificatePolicy = New-Object TrustAllCertsPolicy
}

try {
  $resp = Invoke-RestMethod -Uri $uri -Method Post -ContentType "application/json; charset=utf-8" -Body $json
} catch {
  Write-Error ("enroll failed: " + $_)
}

if ($resp.code -and $resp.code -ne "OK") {
  Write-Error ("API error: " + ($resp | ConvertTo-Json -Compress))
}

$d = $resp.data
if (-not $d.endpoint_id -or -not $d.tenant_id -or -not $d.server_addr) {
  Write-Error "enroll response missing endpoint_id, tenant_id or server_addr"
}

$saddr = $d.server_addr
if ($env:EDR_OVERRIDE_SERVER_ADDR) {
  $saddr = $env:EDR_OVERRIDE_SERVER_ADDR.Trim()
}

$rest = "$api/api/v1"

function Escape-Toml([string]$s) {
  return $s.Replace('\', '\\').Replace('"', '\"')
}

$toml = @"
# Generated by edr_agent_install.ps1

[server]
address              = "$(Escape-Toml $saddr)"
ca_cert              = ""
client_cert          = ""
client_key           = ""
connect_timeout_s    = 10
keepalive_interval_s = 30

[agent]
endpoint_id          = "$(Escape-Toml $d.endpoint_id)"
tenant_id            = "$(Escape-Toml $d.tenant_id)"

[platform]
rest_base_url        = "$(Escape-Toml $rest)"
rest_user_id         = ""
rest_bearer_token    = ""

"@

if ($DryRun) {
  Write-Output $toml
  exit 0
}

$dir = Split-Path -Parent $Output
if ($dir -and -not (Test-Path $dir)) {
  New-Item -ItemType Directory -Path $dir -Force | Out-Null
}
Set-Content -Path $Output -Value $toml -Encoding UTF8
Write-Host "Wrote $Output (endpoint_id=$($d.endpoint_id) tenant_id=$($d.tenant_id) server.address=$saddr)"
