#!/usr/bin/env python3
"""
独立安装器：POST {EDR_API_BASE}/api/v1/enroll，根据响应生成 agent.toml。

环境变量（必填）：
  EDR_API_BASE      平台 REST 根 URL，如 http://127.0.0.1:8080（无尾斜杠）
  EDR_ENROLL_TOKEN  注册 Token 明文

可选：
  EDR_OUTPUT              输出路径，默认当前目录 agent.toml
  EDR_AGENT_VERSION       默认 0.3.0
  EDR_OVERRIDE_SERVER_ADDR  覆盖响应中的 server_addr 写入 [server].address
  EDR_INSECURE_TLS=1      跳过 TLS 证书校验（仅调试）

命令行：
  python3 edr_agent_install.py [--output PATH] [--dry-run]
"""

from __future__ import annotations

import argparse
import json
import os
import platform
import socket
import ssl
import sys
import urllib.error
import urllib.request
from typing import Any, Dict


def _toml_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def _emit_toml(
    server_addr: str,
    endpoint_id: str,
    tenant_id: str,
    rest_base: str,
) -> str:
    lines = [
        "# Generated by edr_agent_install.py",
        "",
        "[server]",
        f'address              = "{_toml_escape(server_addr)}"',
        'ca_cert              = ""',
        'client_cert          = ""',
        'client_key           = ""',
        "connect_timeout_s    = 10",
        "keepalive_interval_s = 30",
        "",
        "[agent]",
        f'endpoint_id          = "{_toml_escape(endpoint_id)}"',
        f'tenant_id            = "{_toml_escape(tenant_id)}"',
        "",
        "[platform]",
        f'rest_base_url        = "{_toml_escape(rest_base)}"',
        'rest_user_id         = ""',
        'rest_bearer_token    = ""',
        "",
    ]
    return "\n".join(lines)


def _detect_os() -> str:
    plat = sys.platform.lower()
    if plat.startswith("win"):
        return "windows"
    if plat == "darwin":
        return "darwin"
    return "linux"


def _hostname() -> str:
    try:
        return socket.gethostname() or "unknown"
    except OSError:
        return "unknown"


def enroll(api_base: str, token: str, agent_version: str) -> Dict[str, Any]:
    api_base = api_base.rstrip("/")
    url = api_base + "/api/v1/enroll"
    body = {
        "token": token,
        "hostname": _hostname(),
        "os": _detect_os(),
        "arch": platform.machine() or "",
        "agent_version": agent_version,
        "ip": "",
    }
    data = json.dumps(body).encode("utf-8")
    req = urllib.request.Request(
        url,
        data=data,
        method="POST",
        headers={"Content-Type": "application/json"},
    )
    ctx = None
    if os.environ.get("EDR_INSECURE_TLS") == "1":
        ctx = ssl._create_unverified_context()
    try:
        with urllib.request.urlopen(req, timeout=120, context=ctx) as resp:
            raw = resp.read().decode("utf-8")
            status = int(resp.status)
    except urllib.error.HTTPError as e:
        err_body = e.read().decode("utf-8", errors="replace")
        print(f"enroll HTTP {e.code}: {err_body}", file=sys.stderr)
        sys.exit(1)

    if status != 201:
        print(f"enroll unexpected status {status}: {raw}", file=sys.stderr)
        sys.exit(1)

    env = json.loads(raw)
    if env.get("code") and env.get("code") != "OK":
        print(f"enroll error: {env.get('message', raw)}", file=sys.stderr)
        sys.exit(1)
    data_obj = env.get("data") or {}
    ep = (data_obj.get("endpoint_id") or "").strip()
    tid = (data_obj.get("tenant_id") or "").strip()
    saddr = (data_obj.get("server_addr") or "").strip()
    if not ep or not tid or not saddr:
        print(f"enroll missing fields: {raw}", file=sys.stderr)
        sys.exit(1)
    override = os.environ.get("EDR_OVERRIDE_SERVER_ADDR", "").strip()
    if override:
        saddr = override
    return {
        "endpoint_id": ep,
        "tenant_id": tid,
        "server_addr": saddr,
        "rest_base": api_base + "/api/v1",
    }


def main() -> None:
    p = argparse.ArgumentParser(description="EDR Agent enroll → agent.toml")
    p.add_argument(
        "-o",
        "--output",
        default=os.environ.get("EDR_OUTPUT", "agent.toml"),
        help="output agent.toml path",
    )
    p.add_argument(
        "--dry-run",
        action="store_true",
        help="print TOML to stdout only",
    )
    args = p.parse_args()

    api_base = os.environ.get("EDR_API_BASE", "").strip()
    token = os.environ.get("EDR_ENROLL_TOKEN", "").strip()
    if not api_base or not token:
        print("Set EDR_API_BASE and EDR_ENROLL_TOKEN", file=sys.stderr)
        sys.exit(2)

    av = os.environ.get("EDR_AGENT_VERSION", "0.3.0").strip() or "0.3.0"
    out = enroll(api_base, token, av)
    text = _emit_toml(
        out["server_addr"],
        out["endpoint_id"],
        out["tenant_id"],
        out["rest_base"],
    )
    if args.dry_run:
        print(text)
        return
    path = args.output
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
    print(
        f"Wrote {path} (endpoint_id={out['endpoint_id']} "
        f"tenant_id={out['tenant_id']} server.address={out['server_addr']})"
    )


if __name__ == "__main__":
    main()
