#!/usr/bin/env python3
"""
构建时把 config/p0_rule_bundle_ir_v1.json（或 .enc 加密版本）编为 C 字节数组。
与 CMake 中 EDR_P0_IR_EMBED 联用；勿手改输出。

支持:
  --input  <.json>      源 JSON 文件或 .enc 加密文件
  --output <.c>         输出 C 字节数组文件
  --no-encrypt          输入是纯文本 JSON（默认自动检测，根据 --input 后缀或内容判断）

当输入文件以 EDR1 魔数开头时，直接作为加密字节嵌入；
否则作为纯文本 JSON 嵌入。
"""

from __future__ import annotations

import argparse
import pathlib


EDR1_MAGIC = b"EDR1"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", type=pathlib.Path, required=True)
    ap.add_argument("--output", type=pathlib.Path, required=True)
    ap.add_argument("--no-encrypt", action="store_true",
                    help="force plaintext JSON mode")
    args = ap.parse_args()
    data = args.input.read_bytes()

    if len(data) > 4 * 1024 * 1024:
        raise SystemExit("input too large (>4 MiB)")

    is_encrypted = not args.no_encrypt and data[:len(EDR1_MAGIC)] == EDR1_MAGIC

    out: list[str] = []
    out.append("/* generated by edr-agent/scripts/gen_p0_rule_ir_embed.py — do not edit */")
    if is_encrypted:
        out.append("/* encrypted format (EDR1): decrypted at runtime */")
    out.append("#include <stddef.h>")
    out.append("")
    out.append("const unsigned char edr_p0_rule_ir_embed_bytes[] = {")
    for i in range(0, len(data), 16):
        row = data[i : i + 16]
        parts = [f"0x{b:02x}" for b in row]
        end = i + 16 >= len(data)
        line = "  " + ", ".join(parts) + ("" if end else ",")
        out.append(line)
    out.append("};")
    out.append("")
    out.append(f"const size_t edr_p0_rule_ir_embed_len = {len(data)};")
    out.append("")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    text = "\n".join(out) + "\n"
    with args.output.open("w", encoding="utf-8", newline="\n") as f:
        f.write(text)

    mode = "encrypted" if is_encrypted else "plaintext"
    print(f"gen_p0_rule_ir_embed: {len(data)} bytes ({mode}) -> {args.output}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
