#!/usr/bin/env python3
"""
build 时把 config/p0_rule_bundle_ir_v1.json 编为 C 字节数组（B1.1 compile-time embed）。
与 CMake 中 EDR_P0_IR_EMBED 联用；勿手改输出。
"""

from __future__ import annotations

import argparse
import pathlib


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", type=pathlib.Path, required=True)
    ap.add_argument("--output", type=pathlib.Path, required=True)
    args = ap.parse_args()
    data = args.input.read_bytes()
    if len(data) > 4 * 1024 * 1024:
        raise SystemExit("input too large (>4 MiB)")
    out: list[str] = []
    out.append("/* generated by edr-agent/scripts/gen_p0_rule_ir_embed.py — do not edit */")
    out.append("#include <stddef.h>")
    out.append("")
    out.append("const unsigned char edr_p0_rule_ir_embed_bytes[] = {")
    for i in range(0, len(data), 16):
        row = data[i : i + 16]
        parts = [f"0x{b:02x}" for b in row]
        end = i + 16 >= len(data)
        line = "  " + ", ".join(parts) + ("" if end else ",")
        out.append(line)
    out.append("};")
    out.append("")
    out.append(f"const size_t edr_p0_rule_ir_embed_len = {len(data)};")
    out.append("")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    text = "\n".join(out) + "\n"
    with args.output.open("w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
