# Shared by the standalone Agent PR/release and monorepo integration workflows.
# Keep each test and its executable together so CTest cannot select an unbuilt
# binary. Platform release gates include these runtime contracts as well.
add_custom_target(agent_runtime_gate_tests)

function(edr_agent_runtime_gate test_name executable_target)
  if(NOT TEST "${test_name}")
    message(FATAL_ERROR "Agent runtime gate test is not registered: ${test_name}")
  endif()
  if(NOT TARGET "${executable_target}")
    message(FATAL_ERROR "Agent runtime gate executable target is missing: ${executable_target}")
  endif()
  add_dependencies(agent_runtime_gate_tests "${executable_target}")
  set_property(TEST "${test_name}" APPEND PROPERTY LABELS agent-runtime-gate)
  set(_edr_agent_runtime_gate_tests ${_edr_agent_runtime_gate_tests} "${test_name}" PARENT_SCOPE)
endfunction()

edr_agent_runtime_gate(command_inbox_persistence test_command_inbox)
edr_agent_runtime_gate(request_signing test_request_signing)
edr_agent_runtime_gate(http_retry_contract test_http_retry)
edr_agent_runtime_gate(command_result_json_contract test_command_result_json)
edr_agent_runtime_gate(event_bus_wait_and_mpmc test_event_bus_mpmc_stress)
edr_agent_runtime_gate(event_batch_max_age test_event_batch_max_age)
edr_agent_runtime_gate(response_capability_manifest_contract test_response_capability_manifest)
edr_agent_runtime_gate(python_installer_config_contract test_python_installer_config_contract)
edr_agent_runtime_gate(detection_decision_combo test_detection_decision)
edr_agent_runtime_gate(detection_regression_scenarios test_detection_regression)
edr_agent_runtime_gate(detection_profile_and_trigger_modes test_detection_profile_trigger)
edr_agent_runtime_gate(detection_sensor_bridge test_detection_sensor_bridge)
edr_agent_runtime_gate(webshell_semantic_rules test_webshell_semantic)
edr_agent_runtime_gate(pmfe_scan_detail_format test_pmfe_detail)
if(OpenSSL_FOUND)
  edr_agent_runtime_gate(command_signature_cross_language test_command_signature_cross_language)
endif()
if(SQLite3_FOUND)
  edr_agent_runtime_gate(storage_queue_sqlite_contract test_storage_queue_sqlite)
endif()
if(EDR_PCRE2_AVAILABLE)
  edr_agent_runtime_gate(p0_source_only_durable_contract test_p0_source_only_durable_contract)
  edr_agent_runtime_gate(p0_rule_ir_record_golden test_p0_rule_ir_record_golden)
endif()
