if(NOT EDR_P0_TEST_CONFIG_AVAILABLE)
  message(FATAL_ERROR "Windows release gate requires external canonical P0 inputs: set EDR_P0_TEST_CONFIG_DIR; no Agent bundle is supplied")
endif()

# One declaration binds each required CTest to its build dependency. Both
# Windows workflows build this target and select this label; neither keeps a
# second executable/test allowlist that can drift when a gate is added.
add_custom_target(windows_release_gate_tests)
add_dependencies(windows_release_gate_tests agent_runtime_gate_tests)
foreach(test_name IN LISTS _edr_agent_runtime_gate_tests)
  set_property(TEST "${test_name}" APPEND PROPERTY LABELS windows-release-gate)
endforeach()

function(edr_windows_release_gate test_name executable_target)
  if(NOT TEST "${test_name}")
    message(FATAL_ERROR "Windows release gate test is not registered: ${test_name}")
  endif()
  if(NOT "${executable_target}" STREQUAL "")
    if(NOT TARGET "${executable_target}")
      message(FATAL_ERROR "Windows release gate executable target is missing: ${executable_target}")
    endif()
    add_dependencies(windows_release_gate_tests "${executable_target}")
  endif()
  set_property(TEST "${test_name}" APPEND PROPERTY LABELS windows-release-gate)
endfunction()

edr_windows_release_gate(agent_update_command_contract test_agent_update_contract)
edr_windows_release_gate(agent_update_packaging_contract test_agent_update_assets)
edr_windows_release_gate(windows_headless_runtime_contract test_windows_headless_runtime_contract)
edr_windows_release_gate(command_registry_and_payload_contract test_command_contract)
edr_windows_release_gate(command_process_identity_and_receipts test_command_process)
edr_windows_release_gate(pmfe_pe_architectures test_pmfe_pe_arch)
edr_windows_release_gate(windows_native_manifest_behavior test_windows_native_manifest)
edr_windows_release_gate(windows_native_uninstall_behavior test_windows_native_uninstall)
edr_windows_release_gate(process_generation_same_handle_command_line test_process_generation_windows)
edr_windows_release_gate(cmd_actor_and_script_artifact test_cmd_actor_artifact)
edr_windows_release_gate(rtq_long_command_windows test_rtq_long_command_windows)
edr_windows_release_gate(rtq_collector_behavior test_rtq_collectors)
edr_windows_release_gate(kernel_file_io_identity test_kernel_file_io_windows)
edr_windows_release_gate(collector_file_read_windows test_collector_file_read_windows)
edr_windows_release_gate(collector_health_disposition_json test_collector_health_json)
edr_windows_release_gate(etw_network_decode_native test_etw_network_decode_windows)
edr_windows_release_gate(etw_process_payload_identity_native test_etw_process_payload_windows)
edr_windows_release_gate(wfas_provider_native test_wfas_provider_windows)
edr_windows_release_gate(security_event_time_native test_security_event_time_windows)
edr_windows_release_gate(security_event_time_failures test_security_event_time_failures_windows)
edr_windows_release_gate(http_telemetry_budget test_http_budget)
edr_windows_release_gate(response_file_security_behavior test_response_file_security)
edr_windows_release_gate(response_forensic_path_contract test_response_forensic_paths)
# This test invokes the checked-in PowerShell script, not a generated EXE.
edr_windows_release_gate(windows_isolation_mock_behavior "")
edr_windows_release_gate(windows_install_compatibility_behavior "")
edr_windows_release_gate(windows_release_collector_pe_closure "")
edr_windows_release_gate(windows_inplace_collector_transaction "")
edr_windows_release_gate(windows_installer_log_redaction "")
edr_windows_release_gate(windows_installer_acl_behavior fd_installer_worker)
edr_windows_release_gate(windows_installer_health_behavior fd_installer_worker)
edr_windows_release_gate(openssl_tls_handshake test_openssl_tls_handshake)
edr_windows_release_gate(windows_task_exit_behavior test_windows_task_exit_fixture)
edr_windows_release_gate(windows_task_trace_environment "")

edr_windows_release_gate(validation_trace_contract test_validation_trace)
